### ISSUE TITLE
Changing theme mode crashes the app

### ISSUE THREAD

**Issue by CrimsonBloodfang** [OlauncherCF/OlauncherCF#152]
#### Short description 
Changing the theme mode from System to Dark, crashes the app. The same goes vice versa or Light to Dark.

#### Steps to reproduce 
1. Long press the home screen
2. Click on theme mode
3. Change from System to Dark
4. See crash

#### Additional elements

https://user-images.githubusercontent.com/68450471/184533162-af5775c8-57fe-4587-97a6-d3eceb0a9440.mp4

>FATAL EXCEPTION: main
Process: app.olaunchercf, PID: 13781
java.lang.RuntimeException: Unable to destroy activity {app.olaunchercf/app.olaunchercf.MainActivity}: java.lang.IllegalStateException: no event down from INITIALIZED
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5155)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5174)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5453)
	at android.app.ActivityThread.-wrap19(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
Caused by: java.lang.IllegalStateException: no event down from INITIALIZED
	at androidx.lifecycle.o.l(SourceFile:19)
	at androidx.lifecycle.o.h(Unknown Source:19)
	at androidx.lifecycle.o.k(Unknown Source:5)
	at i3.e.e(Unknown Source:37)
	at i3.g.k(SourceFile:4)
	at androidx.lifecycle.o$a.a(Unknown Source:14)
	at androidx.lifecycle.o.l(SourceFile:17)
	at androidx.lifecycle.o.h(Unknown Source:19)
	at androidx.lifecycle.o.f(Unknown Source:9)
	at androidx.fragment.app.c0.g(SourceFile:13)
	at androidx.fragment.app.c0.k(SourceFile:17)
	at androidx.fragment.app.o0$a.c(Unknown Source:5)
	at androidx.fragment.app.o0$b.b(SourceFile:2)
	at androidx.fragment.app.o0.e(SourceFile:2)
	at androidx.fragment.app.w.v(SourceFile:3)
	at androidx.fragment.app.w.m(SourceFile:9)
	at androidx.fragment.app.o.onDestroy(SourceFile:1)
	at f.e.onDestroy(Unknown Source:0)
	at android.app.Activity.performDestroy(Activity.java:7615)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1253)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5142)
	... 10 more

**Comment by jooooscha** [comment]
Uff, looks like you are using EMUI? That's a bit hard for me to debug as I do not have a device available. For the record, it does not crash on my phone running lineage os.
I will see what I can do, but without help it could be hard to do

**Comment by jooooscha** [comment]
could write a little note why you closed this issue?
